version: '3.9'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: captcha
      MYSQL_USER: captcha
      MYSQL_PASSWORD: password123
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
    image: ricky92/lb-captcha-service
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=captcha
      - MYSQL_PASS=password123
      - MYSQL_DB=captcha
